TTL_12_HOURS = 12 * 60 * 60
TTL_10_MIN = 10 * 60

PRODUCT_STATS = "product:release_stats"
PRODUCT_STATS_TTL = TTL_12_HOURS

CATEGORY_LIST_PREFIX = "category:list"
CATEGORY_LIST_TTL = TTL_10_MIN

ARTICLE_LIST_PREFIX = "article:list"
ARTICLE_LIST_TTL = TTL_10_MIN

BROADCAST_LIST_PREFIX = "broadcast:list"
BROADCAST_LIST_TTL = TTL_10_MIN
