TTL_24_HOURS = 24 * 60 * 60
TTL_12_HOURS = 12 * 60 * 60
TTL_30_MIN = 30 * 60
TTL_10_MIN = 10 * 60
TTL_5_MIN = 5 * 60

PRODUCT_STATS = "product:release_stats"
PRODUCT_STATS_TTL = TTL_12_HOURS

CATEGORY_LIST_PREFIX = "category:list"
CATEGORY_LIST_TTL = TTL_10_MIN

ARTICLE_LIST_PREFIX = "article:list"
ARTICLE_LIST_TTL = TTL_24_HOURS
ARTICLE_DETAIL_PREFIX = "article:detail"
ARTICLE_DETAIL_TTL = TTL_24_HOURS

BROADCAST_LIST_PREFIX = "broadcast:list"
BROADCAST_LIST_TTL = TTL_24_HOURS
BROADCAST_DETAIL_PREFIX = "broadcast:detail"
BROADCAST_DETAIL_TTL = TTL_24_HOURS

PRODUCT_LIST_PREFIX = "product:list"
PRODUCT_LIST_TTL = TTL_30_MIN
PRODUCT_MEMBER_LIST_TTL = TTL_5_MIN
PRODUCT_DETAIL_PREFIX = "product:detail"
PRODUCT_DETAIL_TTL = TTL_30_MIN
PRODUCT_MEMBER_DETAIL_TTL = TTL_5_MIN
