version: "3.8"

services:
  web:
    image: athenax-backend
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - athenax_network
  
  mongodb:
    image: mongo:7.0.14
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    env_file:
      - .env
    networks:
      - athenax_network
    restart: always
  
  redis:
    image: redis:alpine3.20
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    networks:
      - athenax_network
    command: ["redis-server", "--bind", "0.0.0.0"]

networks:
  athenax_network:
    driver: bridge

volumes:
  mongodb_data:
  mongodb_config:
