version: "3.8"

x-healthcheck-mongodb-template: &mongodbhealthcheck
  healthcheck:
    test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
    interval: 30s
    timeout: 30s
    retries: 3

x-healthcheck-redis-template: &redishealthcheck
  healthcheck:
    test: ["CMD", "redis-cli", "ping"]
    interval: 30s
    timeout: 30s
    retries: 3

services:
  mongodb:
    image: mongo:7.0.14
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    env_file:
      - .env.dev
    networks:
      - athenax_network
    restart: always
    <<: *mongodbhealthcheck

  redis:
    image: redis:alpine3.20
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env.dev
    networks:
      - athenax_network
    command: ["redis-server", "--bind", "0.0.0.0"]
    <<: *redishealthcheck

networks:
  athenax_network:
    driver: bridge

volumes:
  mongodb_data:
  mongodb_config: