"""add status to catogory

Revision ID: 23a6df604d20
Revises: 2e1747c19713
Create Date: 2026-05-05 08:15:01.563406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a6df604d20'
down_revision: Union[str, Sequence[str], None] = '2e1747c19713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('categories', sa.Column('status', sa.String(length=20), nullable=True))
    op.execute("UPDATE categories SET status = 'approved' WHERE status IS NULL")
    op.alter_column('categories', 'status', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'status')
    # ### end Alembic commands ###
