"""add broadcast_id to articles

Revision ID: 2a5c187fc82e
Revises: d8c2454caf3a
Create Date: 2026-06-15 06:32:04.380463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a5c187fc82e'
down_revision: Union[str, Sequence[str], None] = 'd8c2454caf3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('broadcast_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_articles_broadcast_id'), 'articles', ['broadcast_id'], unique=False)
    op.create_foreign_key(None, 'articles', 'broadcasts', ['broadcast_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_index(op.f('ix_articles_broadcast_id'), table_name='articles')
    op.drop_column('articles', 'broadcast_id')
    # ### end Alembic commands ###
