"""add parent_id to categories drop sub_categories from products

Revision ID: 2e1747c19713
Revises: 79be9320f876
Create Date: 2026-04-30 07:49:55.754840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1747c19713'
down_revision: Union[str, Sequence[str], None] = '79be9320f876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('products', 'twitter')
    op.drop_column('products', 'founders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('founders', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('twitter', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('categories', 'parent_id')
    # ### end Alembic commands ###
