"""user roles and profile tables

Revision ID: 3a59f057be38
Revises: ece9f3554a45
Create Date: 2026-03-26 12:07:51.844415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a59f057be38'
down_revision: Union[str, Sequence[str], None] = 'ece9f3554a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Rebuild user_role enum: remove BUILDER, add FOUNDER + INVESTOR, normalise to lowercase.
    # PostgreSQL does not support dropping enum values in-place, so we recreate the type.
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE VARCHAR(20)")
    op.execute("UPDATE users SET role = LOWER(role)")
    op.execute("DROP TYPE IF EXISTS user_role")
    op.execute(
        "CREATE TYPE user_role AS ENUM "
        "('admin', 'user', 'researcher', 'sponsor', 'founder', 'investor')"
    )
    op.execute(
        "ALTER TABLE users ALTER COLUMN role "
        "TYPE user_role USING role::user_role"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investor_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('investor_type', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('sponsor_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_category',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    op.create_table('researcher_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_constraint(op.f('users_lab_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'organization')
    op.drop_column('users', 'lab_id')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('lab_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('organization', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_lab_id_fkey'), 'users', 'labs', ['lab_id'], ['id'])
    op.drop_table('researcher_profiles')
    op.drop_table('user_category')
    op.drop_table('sponsor_profiles')
    op.drop_table('investor_profiles')
    # ### end Alembic commands ###

    # Restore previous enum (uppercase, includes BUILDER, excludes FOUNDER/INVESTOR).
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE VARCHAR(20)")
    op.execute("UPDATE users SET role = UPPER(role)")
    op.execute("DROP TYPE IF EXISTS user_role")
    op.execute(
        "CREATE TYPE user_role AS ENUM "
        "('USER', 'RESEARCHER', 'SPONSOR', 'BUILDER', 'ADMIN')"
    )
    op.execute(
        "ALTER TABLE users ALTER COLUMN role "
        "TYPE user_role USING role::user_role"
    )
