"""add approved_at to products

Revision ID: 45907e1d1e8b
Revises: b6c7f8d79e94
Create Date: 2026-07-07 08:45:56.206780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45907e1d1e8b'
down_revision: Union[str, Sequence[str], None] = 'b6c7f8d79e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.execute(
        "UPDATE products SET approved_at = updated_at WHERE status = 'approved' AND approved_at IS NULL"
    )
    op.create_index('ix_products_status_approved', 'products', ['status', 'approved_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_status_approved', table_name='products')
    op.drop_column('products', 'approved_at')
    # ### end Alembic commands ###
