"""remove product_sector column and enum

Revision ID: 47fb89c85fb6
Revises: 16f1e9c10e9d
Create Date: 2026-04-06 08:14:17.425695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47fb89c85fb6'
down_revision: Union[str, Sequence[str], None] = '16f1e9c10e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sector')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS product_sector")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sector', postgresql.ENUM('AI & Agents', 'Robotics', 'Biotech', 'Crypto & DeFi', 'Developer Tools', 'Infrastructure', 'Climate & Energy', name='product_sector', create_type=True), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
