"""add product_similar table

Revision ID: 699e45db7938
Revises: 45907e1d1e8b
Create Date: 2026-07-08 10:01:58.277758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '699e45db7938'
down_revision: Union[str, Sequence[str], None] = '45907e1d1e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_similar',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('similar_product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('product_id < similar_product_id', name='ck_product_similar_ordering'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['similar_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('product_id', 'similar_product_id')
    )
    op.create_index(op.f('ix_product_similar_created_by_id'), 'product_similar', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_product_similar_updated_by_id'), 'product_similar', ['updated_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_similar_updated_by_id'), table_name='product_similar')
    op.drop_index(op.f('ix_product_similar_created_by_id'), table_name='product_similar')
    op.drop_table('product_similar')
    # ### end Alembic commands ###
