"""add product sub-resource tables

Revision ID: 79be9320f876
Revises: 95eec879710c
Create Date: 2026-04-28 08:47:04.346447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79be9320f876'
down_revision: Union[str, Sequence[str], None] = '95eec879710c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bounties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('tech_label', sa.String(length=100), nullable=True),
    sa.Column('reward_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('open', 'completed', 'cancelled', name='bounty_status'), server_default='open', nullable=False),
    sa.Column('external_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bounties_created_by_id'), 'bounties', ['created_by_id'], unique=False)
    op.create_index('ix_bounties_product_id', 'bounties', ['product_id'], unique=False)
    op.create_index('ix_bounties_status', 'bounties', ['product_id', 'status'], unique=False)
    op.create_index(op.f('ix_bounties_updated_by_id'), 'bounties', ['updated_by_id'], unique=False)
    op.create_table('product_backers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_backers_created_by_id'), 'product_backers', ['created_by_id'], unique=False)
    op.create_index('ix_product_backers_product_id', 'product_backers', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_backers_updated_by_id'), 'product_backers', ['updated_by_id'], unique=False)
    op.create_table('product_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.Enum('website', 'github', 'twitter', 'docs', 'demo', 'discord', name='product_link_type'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'link_type', name='uq_product_links_product_link_type')
    )
    op.create_index(op.f('ix_product_links_created_by_id'), 'product_links', ['created_by_id'], unique=False)
    op.create_index('ix_product_links_product_id', 'product_links', ['product_id'], unique=False)
    op.create_index('ix_product_links_type', 'product_links', ['product_id', 'link_type'], unique=False)
    op.create_index(op.f('ix_product_links_updated_by_id'), 'product_links', ['updated_by_id'], unique=False)
    op.create_table('product_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'video_hosted', 'video_youtube', name='product_media_type'), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_media_created_by_id'), 'product_media', ['created_by_id'], unique=False)
    op.create_index('ix_product_media_product_id', 'product_media', ['product_id'], unique=False)
    op.create_index('ix_product_media_sort', 'product_media', ['product_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_product_media_updated_by_id'), 'product_media', ['updated_by_id'], unique=False)
    op.create_table('product_team',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role_label', sa.String(length=150), nullable=True),
    sa.Column('bio_note', sa.String(length=300), nullable=True),
    sa.Column('twitter_url', sa.String(length=200), nullable=True),
    sa.Column('github_url', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='team_member_status'), server_default='pending', nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_team_created_by_id'), 'product_team', ['created_by_id'], unique=False)
    op.create_index('ix_product_team_product_id', 'product_team', ['product_id'], unique=False)
    op.create_index('ix_product_team_status', 'product_team', ['product_id', 'status'], unique=False)
    op.create_index(op.f('ix_product_team_updated_by_id'), 'product_team', ['updated_by_id'], unique=False)
    op.create_table('product_voices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('author_handle', sa.String(length=100), nullable=False),
    sa.Column('author_name', sa.String(length=150), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_voices_created_by_id'), 'product_voices', ['created_by_id'], unique=False)
    op.create_index('ix_product_voices_product_id', 'product_voices', ['product_id'], unique=False)
    op.create_index('ix_product_voices_sort', 'product_voices', ['product_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_product_voices_updated_by_id'), 'product_voices', ['updated_by_id'], unique=False)
    op.add_column('product_comments', sa.Column('pinned', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('products', sa.Column('short_desc', sa.String(length=150), nullable=True))
    # Migrate existing github/demo values to product_links before dropping columns
    op.execute("""
        INSERT INTO product_links (product_id, link_type, url, created_at, updated_at)
        SELECT id, 'github', github, now(), now()
        FROM products WHERE github IS NOT NULL AND github != ''
    """)
    op.execute("""
        INSERT INTO product_links (product_id, link_type, url, created_at, updated_at)
        SELECT id, 'demo', demo, now(), now()
        FROM products WHERE demo IS NOT NULL AND demo != ''
    """)
    op.drop_column('products', 'demo')
    op.drop_column('products', 'github')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('github', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('demo', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('products', 'short_desc')
    op.drop_column('product_comments', 'pinned')
    op.drop_index(op.f('ix_product_voices_updated_by_id'), table_name='product_voices')
    op.drop_index('ix_product_voices_sort', table_name='product_voices')
    op.drop_index('ix_product_voices_product_id', table_name='product_voices')
    op.drop_index(op.f('ix_product_voices_created_by_id'), table_name='product_voices')
    op.drop_table('product_voices')
    op.drop_index(op.f('ix_product_team_updated_by_id'), table_name='product_team')
    op.drop_index('ix_product_team_status', table_name='product_team')
    op.drop_index('ix_product_team_product_id', table_name='product_team')
    op.drop_index(op.f('ix_product_team_created_by_id'), table_name='product_team')
    op.drop_table('product_team')
    op.drop_index(op.f('ix_product_media_updated_by_id'), table_name='product_media')
    op.drop_index('ix_product_media_sort', table_name='product_media')
    op.drop_index('ix_product_media_product_id', table_name='product_media')
    op.drop_index(op.f('ix_product_media_created_by_id'), table_name='product_media')
    op.drop_table('product_media')
    op.drop_index(op.f('ix_product_links_updated_by_id'), table_name='product_links')
    op.drop_index('ix_product_links_type', table_name='product_links')
    op.drop_index('ix_product_links_product_id', table_name='product_links')
    op.drop_index(op.f('ix_product_links_created_by_id'), table_name='product_links')
    op.drop_table('product_links')
    op.drop_index(op.f('ix_product_backers_updated_by_id'), table_name='product_backers')
    op.drop_index('ix_product_backers_product_id', table_name='product_backers')
    op.drop_index(op.f('ix_product_backers_created_by_id'), table_name='product_backers')
    op.drop_table('product_backers')
    op.drop_index(op.f('ix_bounties_updated_by_id'), table_name='bounties')
    op.drop_index('ix_bounties_status', table_name='bounties')
    op.drop_index('ix_bounties_product_id', table_name='bounties')
    op.drop_index(op.f('ix_bounties_created_by_id'), table_name='bounties')
    op.drop_table('bounties')
    # ### end Alembic commands ###
