"""add product grant table

Revision ID: 9f54c1895cbd
Revises: 671a2baf0ba3
Create Date: 2026-07-03 06:33:37.773040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f54c1895cbd'
down_revision: Union[str, Sequence[str], None] = '671a2baf0ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_grants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_grants_created_by_id'), 'product_grants', ['created_by_id'], unique=False)
    op.create_index('ix_product_grants_product_id', 'product_grants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_grants_updated_by_id'), 'product_grants', ['updated_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_grants_updated_by_id'), table_name='product_grants')
    op.drop_index('ix_product_grants_product_id', table_name='product_grants')
    op.drop_index(op.f('ix_product_grants_created_by_id'), table_name='product_grants')
    op.drop_table('product_grants')
    # ### end Alembic commands ###
