"""add imported, email, twitter columns to products

Revision ID: a21667fcd7e2
Revises: cdd53ad36286
Create Date: 2026-04-13 07:28:54.147178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a21667fcd7e2'
down_revision: Union[str, Sequence[str], None] = 'cdd53ad36286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('imported', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('products', sa.Column('email', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('twitter', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'twitter')
    op.drop_column('products', 'email')
    op.drop_column('products', 'imported')
    # ### end Alembic commands ###
