"""preserve tag casing with case-insensitive unique index on lower(name)

Revision ID: ac5d9c9a5e9d
Revises: e62b1a1b6475
Create Date: 2026-05-14 12:49:54.143066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac5d9c9a5e9d'
down_revision: Union[str, Sequence[str], None] = 'e62b1a1b6475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tags_name_key'), 'tags', type_='unique')
    op.create_index('ix_tags_name_lower', 'tags', [sa.literal_column('lower(name)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tags_name_lower', table_name='tags')
    op.create_unique_constraint(op.f('tags_name_key'), 'tags', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
