"""remove author_handle from product_voices, make source_url required

Revision ID: b6c7f8d79e94
Revises: 9c1d4e7a2b3f
Create Date: 2026-07-07 07:50:16.748508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c7f8d79e94'
down_revision: Union[str, Sequence[str], None] = '9c1d4e7a2b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE product_voices SET source_url = '' WHERE source_url IS NULL")
    op.alter_column('product_voices', 'source_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('product_voices', 'author_handle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_voices', sa.Column('author_handle', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('product_voices', 'source_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###
