"""add broadcast domain with broadcast_tag association

Revision ID: c2f4638013ca
Revises: ac5d9c9a5e9d
Create Date: 2026-05-22 12:40:46.457333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2f4638013ca'
down_revision: Union[str, Sequence[str], None] = 'c43d4e7898a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('embed_url', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('broadcast_type', sa.Enum('whitepaper', 'livestream', 'roundtable', name='broadcast_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='broadcast_status'), server_default='draft', nullable=False),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('origin_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_broadcasts_created_by_id'), 'broadcasts', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_broadcasts_updated_by_id'), 'broadcasts', ['updated_by_id'], unique=False)
    op.create_table('broadcast_tag',
    sa.Column('broadcast_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('broadcast_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broadcast_tag')
    op.drop_index(op.f('ix_broadcasts_updated_by_id'), table_name='broadcasts')
    op.drop_index(op.f('ix_broadcasts_created_by_id'), table_name='broadcasts')
    op.drop_table('broadcasts')
    # ### end Alembic commands ###
