"""add perf indexes for product feeds and article list

Revision ID: d8c2454caf3a
Revises: e2b3c4d5f6a7
Create Date: 2026-06-08 11:04:16.472594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c2454caf3a'
down_revision: Union[str, Sequence[str], None] = 'e2b3c4d5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_articles_status_published', 'articles', ['status', 'published_at'], unique=False)
    op.create_index('ix_product_bookmarks_user_created', 'product_bookmarks', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_product_votes_user_created', 'product_votes', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_products_status_created', 'products', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_status_created', table_name='products')
    op.drop_index('ix_product_votes_user_created', table_name='product_votes')
    op.drop_index('ix_product_bookmarks_user_created', table_name='product_bookmarks')
    op.drop_index('ix_articles_status_published', table_name='articles')
    # ### end Alembic commands ###
