"""add product_related table

Revision ID: df9e766e3ea8
Revises: 26206aa8b2f7
Create Date: 2026-07-10 05:10:45.553640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9e766e3ea8'
down_revision: Union[str, Sequence[str], None] = '26206aa8b2f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_related',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('related_product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('product_id < related_product_id', name='ck_product_related_ordering'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('product_id', 'related_product_id')
    )
    op.create_index(op.f('ix_product_related_created_by_id'), 'product_related', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_product_related_updated_by_id'), 'product_related', ['updated_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_related_updated_by_id'), table_name='product_related')
    op.drop_index(op.f('ix_product_related_created_by_id'), table_name='product_related')
    op.drop_table('product_related')
    # ### end Alembic commands ###
