"""add user verification and reset hash

Revision ID: ecc46b3d037f
Revises: d7126ed15479
Create Date: 2026-03-22 07:14:55.536120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc46b3d037f'
down_revision: Union[str, Sequence[str], None] = 'd7126ed15479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('verified', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column('users', sa.Column('verification_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_hash', sa.String(length=255), nullable=True))
    op.alter_column('users', 'verified', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_hash')
    op.drop_column('users', 'verification_hash')
    op.drop_column('users', 'verified')
    # ### end Alembic commands ###
